### PR TITLE
Data parallel Plugin

### PR DESCRIPTION
**Pull request by skanur**
I think the first version of the data-parallel detection plugin is completed and can be merged with `develop` and subsequently with `master` branch, (if you deem fit and complies with your release cycle). 

The implementation details of the plugin is [here](http://tucs.fi/publications/view/?pub_id=tKaLiEr17a) and is also part of a publication at DASIP-2017 which will be published soon. The plugin documentation is updated accordingly.

Let me know how I can help to make the merge process easier.

### CODE REVIEW

**Comment by antoine-morvan** [comment]
Hi @skanur 

As it is, your plug-in does not respect the guidelines (see https://github.com/preesm/preesm/blob/master/releng/README.md#add-a-new-plugin). I will do the changes and come back to you later.

**Comment by skanur** [comment]
Hey!

Thanks for the link. Unfortunately, I couldn't understand beyond point 2 of the list "Add new plugin". So, I'll wait for your changes.

**Comment by antoine-morvan** [comment]
Hi, 

I did following changes:
- Rebase on latest develop;
- Move the plugin to /plugins/
- Make it a Maven project and add it into the parent Pom;
- Split it in 2: one for the code, on for the tests;
- Rename it "fi.abo.preesm.dataprallel.*" (and packages too);
- Rename the task (see comment below);
- Move xtend sources to xtend-src/ source folder;
- Cleanup the code;
- Remove unused dependencies;
- Add vendor info (ABO.fi) and fix headers;

Regarding the task name, I let the 2 IDs live, but only one should remain (fi.abo... preferably). I let the 2 live for now so that your existing workflows do no break.

Can you pull (-force since I forced the push) and test it ? You will have to import the two projects in your workspace again because of the move/rename.

We can setup integration tests that will run a workflow on a project (see the project **org.ietr.preesm.test.it**). I can do it if you provide us a small demo Preesm project that uses your task.

Also, could you write a one or two lines release note entry ?

Let me know if you have any issue.

Kind regards.

**Comment by skanur** [comment]
Hey,

The name `fi.abo.preesm.dataparallel` is OK, both for the task ID and the packages. I've made the changes accordingly.

I have pulled the changes and tested them, everything is working fine. 

On demo, how do you want me to provide it? I have some 12-15 graphs and it would be nice if your integration test runs them all, but it is not necessary. Shall I upload a tar containing the project here?

On release entry, under _New Features_: 
> Front-end SDF graph analysis plugin that checks if the given SDF graph can be executed in data-parallel fashion i.e. for each actor of the graph, run all its instances in parallel. 

Finally, I note the new license header that you've added. This has raised an important issue of licensing and copyright at our end. It is still unclear if Abo Akademi or I am the copyright holder. So until this is sorted out, I guess we have to hold the pull request. This may take two to three weeks. If you have some concerns about the licensing at your end, let me know and we can discuss this issue. 

Until this is sorted out, I suggest we work towards fixing rest of the issues.

Warm regards,

**Comment by antoine-morvan** [comment]
Hi, 

First, please ignore the travis check failures (I am experimenting a bit right now).

About your last commit, why does the test plug-in need to have dependencies to following ?
```
+ jep;bundle-version="2.40.0",
+ com.github.yannrichet.JMathArray;bundle-version="1.0.0",
+ gov.nist.math.jama;bundle-version="1.0.3"
```
when it executes flawlessly without.

For the tests, you can send me a tar with everything and I will figure out a way to add them (they will be pushed on the git repo, make sure there is nothing confidential within).

Regarding the license issue, for sake of clarity and simplicity, everything hosted on the Preesm repo will be licensed under the CeCILL-C license. Other than that, I do not have any concern.

Best.

**Comment by skanur** [comment]
Hey,

You are right with the test dependencies. I was running them incorrectly using only JUnit, while I guess the correct way to run them is using JUnit-Plugin Test. I realized the difference today and I've fixed them. 

Also, please find the tar file containing examples -> [data_par_eg.zip](https://github.com/preesm/preesm/files/1401001/data_par_eg.zip)

If everything is ok, then we have to wait until the copyright ownership is decided. CeCILL license should be OK, but I'll let the lawyers figure that out and give us an input on how to proceed.

Warm regards,

**Comment by skanur** [comment]
I added Abo Akademi as the copyright holder. The branch is ready to be merged from my side.

**Comment by skanur** [comment]
Hey!
I have started working on the issues. However, as my setup is quite old, when I try to update the Developer requirements as listed in __Install_ XTend, GEF SDK, Graphiti, Maven, DFTools, ..._ [here](http://preesm.sourceforge.net/website/index.php?id=building-preesm), the installer encounters a problem with the following message:

```
An error occurred while collecting items to be installed
session context was:(profile=_home_sudeep_workspace_manualInstalledPacks_eclipse_neon_preesm_eclipse_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://preesm.sourceforge.net/eclipse/update-site/plugins/org.sonarlint.eclipse.core_3.3.1.201712071600.jar.
Connection reset
```

I have tried few times already and I have a good internet connection here. Is there an issue at your end?

**Pull request closed without merging**
